import { makeStyles } from "@material-ui/core/styles";

export const lessonMediaStylesDesktop = makeStyles((theme) => ({
  scroll: {
    backgroundColor: theme.palette.primary.dark,
    position: "relative",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    overflow: "auto",
    whiteSpace: "nowrap",
  },
  image: {
    position: "relative",
    top: 0,
    left: 0,
    minWidth: 400,
  },
  innerZoomOverlay: {
    position: "absolute",
    zIndex: 1,
    bottom: 0,
    right: 0,
    height: 50,
    width: 50,
    color: "white",
  },
  centerLock: {
    position: "absolute",
    top: "50%",
    left: "calc(50% + 0px)",
    transform: "translate(-50%, -50%)",
  },
  released: {
    marginTop: "-30",
    transform: "translate(0%, -60%)",
    padding: 10,
    height: 10,
    width: "140%",
  },
  censored: {
    borderRadius: 10,
    background: theme.palette.primary.main,
    color: "white",
    padding: 10,
    height: 10,
    width: "calc(100% - 20px)",
    position: "relative",
    borderColor: "orange",
    borderWidth: 2,
    borderStyle: "solid",
  },
  survey: {
    padding: theme.spacing(2),
    maxWidth: 500,
    marginLeft: "auto",
    marginRight: "auto",
  },
  mediaRoot: {},
  mediaDefault: {
    height: "98%",
    width: "98%",
  },
  mediaSurveySays: {
    height: "98%",
    width: "98%",
  },
}));

export const lessonMediaStylesMobile = makeStyles((theme) => ({
  scroll: {
    backgroundColor: theme.palette.primary.dark,
    position: "relative",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    overflow: "auto",
    whiteSpace: "nowrap",
  },
  image: {
    position: "relative",
    top: 0,
    left: 0,
    minWidth: 400,
  },
  innerZoomOverlay: {
    position: "absolute",
    zIndex: 1,
    bottom: 0,
    right: 0,
    height: 50,
    width: 50,
    color: "white",
  },
  centerLock: {
    position: "absolute",
    top: "50%",
    left: "calc(50% + 0px)",
    transform: "translate(-50%, -50%)",
  },
  released: {
    marginTop: "-30",
    transform: "translate(0%, -60%)",
    padding: 10,
    height: 10,
    width: "140%",
  },
  censored: {
    borderRadius: 10,
    background: theme.palette.primary.main,
    color: "white",
    padding: 10,
    height: 10,
    width: "calc(100% - 20px)",
    position: "relative",
    borderColor: "orange",
    borderWidth: 2,
    borderStyle: "solid",
  },
  survey: {
    padding: theme.spacing(2),
    maxWidth: 500,
    marginLeft: "auto",
    marginRight: "auto",
  },
  mediaRoot: {},
  mediaDefaultMobile: {
    height: "35%",
  },
  mediaSurveySaysMobile: {
    height: "30%",
    width: "100%",
  },
}));
